# Generated by Django 3.1.7 on 2021-03-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SitSpots', '0002_auto_20210304_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
