# Generated by Django 3.1.7 on 2021-03-05 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SitSpots', '0003_auto_20210304_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zone_posts', to='SitSpots.zone'),
        ),
    ]
