# Generated by Django 3.1.7 on 2021-03-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SitSpots', '0006_auto_20210304_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='icon',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
