# Generated by Django 3.1.7 on 2021-03-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SitSpots', '0007_comment_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lat',
            field=models.DecimalField(decimal_places=18, default=None, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='lng',
            field=models.DecimalField(decimal_places=18, default=None, max_digits=25, null=True),
        ),
    ]
